"""initial

Revision ID: 4d51f93d0ea5
Revises: 
Create Date: 2026-04-09 19:17:43.873041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d51f93d0ea5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('target_scope', sa.JSON(), nullable=False),
    sa.Column('target_out_of_scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused_at_gate', 'complete', 'aborted', name='engagementstatus'), nullable=False),
    sa.Column('gate_status', sa.Enum('gate_1', 'gate_2', 'gate_3', 'complete', name='gatestatus'), nullable=False),
    sa.Column('semantic_model', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('recon', 'logic_modeler', 'probe', 'evasion', 'deep_exploit', 'child', 'validator', name='agenttype'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('spawned_reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'bidding', 'running', 'terminated', 'completed', name='agentstatus'), nullable=False),
    sa.Column('current_task_id', sa.UUID(), nullable=True),
    sa.Column('signal_history', sa.JSON(), nullable=False),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('app_type', sa.String(), nullable=False),
    sa.Column('attack_class', sa.String(), nullable=False),
    sa.Column('technique', sa.String(), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed', 'false_positive', 'inconclusive', name='outcometype'), nullable=False),
    sa.Column('evasion_used', sa.String(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('required_confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'bidding', 'assigned', 'awaiting_human_gate', 'complete', 'rejected', name='taskstatus'), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('estimated_probes', sa.Integer(), nullable=False),
    sa.Column('noise_level', sa.Enum('low', 'medium', 'high', name='noiselevel'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('won', 'lost', 'expired', name='bidoutcome'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vulnerability_class', sa.String(), nullable=False),
    sa.Column('affected_surface', sa.String(), nullable=False),
    sa.Column('reproduction_steps', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity'), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'validated', 'rejected', name='validationstatus'), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('bids')
    op.drop_table('tasks')
    op.drop_table('knowledge_entries')
    op.drop_table('agents')
    op.drop_table('engagements')
    # ### end Alembic commands ###
